# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default='padrao', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='padrao', max_length=50),
            preserve_default=False,
        ),
    ]
