# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='courses/images', verbose_name='Imagem'),
        ),
    ]
